# Generated by Django 5.1.5 on 2025-02-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangodeploy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
